name: Flutter Android Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      # 備份自訂程式
      - run: |
          mv lib lib_backup
          cp pubspec.yaml pubspec_backup.yaml

      # 重新產生正式 Flutter 專案骨架
      - run: flutter create . --platforms android --project-name ranked_ball_game --overwrite

      # 還原自訂程式
      - run: |
          rm -rf lib
          mv lib_backup lib
          mv pubspec_backup.yaml pubspec.yaml

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
